### ISSUE TITLE
Create React JS Application

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/ReactChat#2]
### Create React JS Application

**Goals**
Use the create-react-app ❤️ tool to create a react project from the command line
Install and configure the required modules

**Tasks**
- [ ] run the `npx create-react-app reactchat `command to create the react project
- [ ] cd into the reactchat project folder cd `reactchat`
- [ ] open the project in the  VS Code
- [ ] run the command `npm start` to start the application
- [ ] install Firebase module to access firebase/firestore, Reactstrap to use Bootstrap within React JS, react-scroll-to-bottom  scrolling to the bottom of the chatbox and moment for formatting date
