### ISSUE TITLE
Add React Router DOM

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/ReactChat#4]
### Add React Router DOM

**Goals**
Building navigation flow for the project. The page has a few pages Login, Room List, Add Room, and Chat Room pages. We need to create a navigation flow for them

**Tasks**
- [ ] Create the **component** folder
- [ ] Create the Login component
- [ ] Create the RoomList component 
- [ ] Create the AddRoom component
- [ ] Create the ChatRoom component
- [ ] Edit `src/index.js` and import the Bootstrap and BrowserRouter
- [ ] In the `src/index.js` wrap the `<App/>` component inside the `<BrowserRouter>` component
- [ ] In the `src/App.js`, import BrowserRouter, Switch, Route, Redirect, useLocation from `react-router-dom` and Import all the components we created so far.
- [ ]Modify the App function to add the **React Router** that maps to the imported React components with the default landing page redirect to RoomList component
- [ ] Implement the SecureRoute component to add a security filtering. The component filters users so that only logged-in users can access the secured component.
