### ISSUE TITLE
Implementing Login page

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/ReactChat#5]
### Implementing Login page

**Goals**
The login component will contain the form with an input text and a submit button. The data entered in the form will be submitted to the Firebase Realtime-Database to check the existing nickname first then save to Firebase if there's no matching nickname found. 

**Tasks**
- [ ] Open and edit `src/components/Login.js` then import  `React, { useState }` from React, `useHistory`  from             
    `react-router-dom`, `Jumbotron, Spinner, Form, Button, FormGroup, Label,  Input` from `reactstrap ` and the firebase module that we create in the `src/Firebase.js `file

- [ ] Create React function component called Login
- [ ] Declare the variables for the required form field, loading spinner trigger, history, and Firebase Database reference.
- [ ] Render the view of the login page by adding a return that contains HTML tags with React components.
- [ ] Add a function to handle the input value changes.
- [ ] Add a function to submit the data to the Firebase realtime-database.
- [ ] Render the view of the login page
