### ISSUE TITLE
Implement Add a New Room Feature

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/ReactChat#7]
### Add a New Room Feature

**Goals**
Implement **Add a New Room**  feature to the application

**Tasks**

- [ ] Create AddRoom component in `src/components/AddRoom.js` then add the required imports.
- [ ] Add a View to this Add Room form
- [ ] Declare the required state variables
- [ ] Add a function to save the room data in the Firebase Realtime database
- [ ] Add a function to handle the input value change
