### ISSUE TITLE
Implement Chat Room

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/ReactChat#8]
### Implement Chat Room

**Goals**
The chat room implementation will contain a chat-box, a list of online users, and a message form.

**Tasks**

- [ ] Create React function component **ChatRoom** in `src/components/ChatRoom.js`
- [ ] Add the required import to the component
- [ ] Add a useEffect that loads the chats data from the FRD
- [ ] Add another useEffect that loads the user's data from the FRD
- [ ] Create a utility function that extracts the Firebase response to the array of object.
- [ ] Create the view for the ChatRoom
- [ ] Create a CSS file to be used on the ChatRoom
- [ ] Add the function to exit the Chat Room while sending status data to the Firebase
- [ ] Add a function that submits a new message  from the message form to the Firebase database
- [ ] Add a message to handle the input changes
